# Build and push an image to Azure Docker hub
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '5b3247f2-254a-4ef5-9d22-e864edbace26'
  imageRepository: 'kwetteruserservice'
  containerRegistry: 'kwetterregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Main
  displayName: Setup build analyse and deploy
  pool:
    vmImage: windows-latest  
  jobs:
  - job: Setup
    displayName: Setup build analyse and deploy
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        feedsToUse: 'select'
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloudUsers'
        organization: 'kwetter-fontys'
        scannerMode: 'MSBuild'
        projectKey: 'Kwetter-Fontys_kwetter_user_service'
        projectName: 'Kwetter user service'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.csproj'
        arguments: '--collect "Code Coverage"'
        testRunTitle: 'All tests'
    - task: dependency-check-build-task@6
      inputs:
        projectName: 'kwetter-user-service'
        scanPath: '$(Build.SourcesDirectory)/**/bin/Debug/net6.0/*.dll'
        format: 'HTML, JUNIT'
        failOnCVSS: '8'
        
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUNIT'
        testResultsFiles: '**/*-junit.xml'
        searchFolder: '$(Common.TestResultsDirectory)'
        failTaskOnFailedTests: true
        testRunTitle: 'Dependency check'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

- stage: Deploy
  pool:
    vmImage: $(vmImageName)
  jobs:
  - job: Deploy
    displayName: Deploy to docker
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'sebananas/userservice'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
